#!/bin/bash
# cribbed from Conner McD

programs=$(pacman --color always -Sl | fzf --layout=reverse --multi --ansi -m --preview="pacman -Si {2}" --bind=space:toggle-preview | cut -f 2 -d " " | tr '\n' ' ' | sed 's/\x1b\[[0-9;]*[a-zA-Z]//g')
echo -e "selected: \n${programs}"

if [ -n "$programs" ]; then
	sudo pacman --needed -S $programs
fi
