#!/bin/bash
# search for an installed package and show it's database info

program=$(pacman -Qq | fzf -m --preview="pacman -Qi {}" --bind=space:toggle-preview)

if [ -n "$program" ]; then
	pacman -Qi "$program"
fi
