#!/bin/bash
# script for building and checking AUR packages
# psuedo-code:
# clean chroot
# makepkg -sc
# namcap foo

# https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot


