#!/bin/bash
# cribbed from:

# config vars
HOME="/home/liam/" #dont forget trailing slash!
DEST="/run/media/liam/essd_backup/Backup_Archbook/liam/"

if [[ -d $DEST ]];
then

    declare -a StringArray=("Documents" "Music" "Videos" "Pictures" "Downloads")

    # sync
    for dir in "${StringArray[@]}"; do
      rsync -rauP $HOME"${dir}" "${DEST}"
      # echo $HOME"${dir}"
    done
else
    echo "backup dir not found"
fi

