#!/bin/bash
# Purpose: a script for copying from GoogleDrive using rclone
# Input  : a folder from Google Drive to copy onto this computer
# Author : Liam Timms
MINPARAMS=1

localpath=~/Documents/GoogleDrive/
inputfolder="${currentfolder#$localpath}"

#Usage(){ echo "$0; This script requires a source google drive folder"; exit 1; }
operation="$1"
inputfolder="$2"

# rclone syntax is like:
# Syntax: [options] subcommand <parameters> <parameters...>

# STATUS
if [ "$operation" == "status" ]; then
	rclone check "$PWD" remote:"${PWD##*/GoogleDrive/}"
	exit 1
# CLONE
elif [ "$operation" == "clone" ]; then
	echo "Cloning into ~/Documents/GoogleDrive/"
	echo "$inputfolder"
	rclone copy remote:"$inputfolder" ~/Documents/GoogleDrive/$inputfolder -P
	exit 2
# PUSH
elif [ "$operation" == "push" ]; then
	echo "pushing local version of:"
	echo "$inputfolder"
	rclone copy "$PWD" remote:"${PWD##*/GoogleDrive/}"
# PULL
elif [ "$operation" == "pull" ]; then
	echo "pulling remote version of:"
	echo "${PWD##*/GoogleDrive/}"
	rclone sync remote:"${PWD##*/GoogleDrive/}" "$PWD"
fi

# LIST

# TODO: add check, push, pull, capabilities. Maybe just make this like git?
# rclone check source:path dest:path
# push - rclone copy source:localpath dest:path
