#!/bin/bash
# Moves each sentence of a markdown file to a new line for easier git tracking.
MINPARAMS=1

Usage(){ echo "$0; This script requires a source file"; exit 1; }
inputfile=$1
outputfile=${inputfile/.md/_git.md}
c="sed 's/\([.?!;]\)\s\([A-Z]\)/\1\n\2/g' ${inputfile} > ${outputfile}"
echo "${inputfile}" | entr -sc "date "+%T" ; echo ' - updating git markdown' ; ${c}"
