#!/bin/bash
# greets me, tells me the weather, lists todo list, gives time for coffee, and then starts
# pomodoro timer and opens todo list.

espeak "Good morning, Liam."
curl wttr.in
grep "\[\s\]" ~/Documents/notes/todo.md
sleep 5m
gnome-pomodoro --start
notes todo
