#!/bin/bash
# a script for Swaybar to display if archlinux updates are needed

n=$(checkupdates | grep -v hask | wc -l)
p=$(expr $n \> 30)
percentage=$(expr $p \* 100)

printf '%s\n' '{"class":"'"$percentage"'","percentage":'"$percentage"'}'
