#!/bin/bash
# Purpose: creates markdown file with headings for note taking in notes folder
# Input  : name of the markdown file
# Author : Liam Timms
# Date   : 9/13/19
# Version: 1
MINPARAMS=1

Usage(){ echo "$0; This script requires a file name"; exit 1; }
filename=~/Documents/notes/$1.md
touch filename
cat <<EOT >> ${filename}
% title
% Liam Timms
% \today
---
theme: Singapore
geometry: margin=.5in
---
EOT

nvim ${filename}
