#!/bin/bash
# Purpose: creates markdown file with headings for note taking in notes folder
# Input  : name of the markdown file
# Author : Liam Timms
# Date   : 9/13/19
# Version: 1

if [ -z "$1" ]; then
    cd ~/Documents/notes
    filename=$(ls *.md | fzf -m --preview='head -10 {}')
    nvim ${filename}
else

filename=~/Documents/notes/$1.md

if [ -f "${filename}" ]; then
nvim ${filename}
else

touch ${filename}
cat <<EOT >> ${filename}
% title
% Liam Timms
% \today
---
theme: Singapore
geometry: margin=.5in
---
EOT

nvim ${filename}

fi

fi


