#!/bin/bash
# Plays video with MPV in corner of the screen.
MINPARAMS=1

Usage() {
    echo "$0; This script requires a source file"
    exit 1
}
mpv --autofit=800 --geometry=100%:100% --ontop "${1}"
