#!/bin/bash
# Purpose: converts markdown into formatted text pdf and a pdf slide-show
# Input  : a markdown file for use with pandoc
# Author : Liam Timms

MINPARAMS=1

Usage(){ echo "$0; This script require a source file"; exit 1; }
inputfile=$1
# read inputfile
outputfile_slides=${inputfile/.md/_slides.pdf}
outputfile_notes=${inputfile/.md/_notes.pdf}
echo "working..."
pandoc "$inputfile" -t beamer -o "$outputfile_slides"
pandoc -N "$inputfile" -o "$outputfile_notes"
echo "done"
