#!/bin/bash
#
# Read in TWIX tag from a Siemens raw data file
#

# Check for existence of input file
if [ ! -f $1 ]; then
	echo "Error: file $1 does not exist"
	exit 1
fi

# Check it is a Siemens raw data file

# Assign input arguments
file=$1
# tag=$2

# Get the tag value
name=$(head -n 150 $file | grep --binary-files=text '"tPatientName">' | awk -F'"' '{print $4}' | tr -d ',' | sed 's/\^/_/g; s/ /_/g')
ID=$(head -n 150 $file | grep --binary-files=text '"PatientID">' | awk -F'"' '{print $4}' | tr -d ',' | sed 's/\^/_/g; s/ /_/g')
echo $name $ID
