#!/bin/bash
# Just a useful pandoc commmand with some cleaning after
MINPARAMS=1

Usage(){ echo "$0; This script requires a source file"; exit 1; }
inputfile=$1
# read inputfile
outputfile=${inputfile/.docx/.md}
outputmedia=${inputfile/.docx/}
echo "working..."
pandoc --extract-media $outputmedia --wrap=none -N $inputfile -o $outputfile
# move every sentence to new line to allow easier git tracking
sed -i 's/[.!?]  */&\n/g' $outputfile
echo "done"

